name: GHA - Deploy to S3

on:
  push:
    branches:
      - master
    paths:
      - 'static/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Deploy to S3
        run: |
          aws s3 cp ${{ github.workspace }}/static/ s3://andrewburton.biz/ --recursive

      # # UNCOMMENT THE FOLLOWING TO ENABLE CLOUDFRONT CACHE INVALIDATION
      # - name: Invalidate CloudFront Cache
      #   run: |
      #     aws cloudfront create-invalidation \
      #     --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
      #     --paths "/*"